### ISSUE TITLE
Ratio functionality

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#100]
opened by @nb152

In our last osm data quality meeting, we realized that it would be useful to able to calculate the ratio between two groups of objects e.g. the ratio between residential roads ("highway"="residential") and all roads ("highway"). Right now one would have to make two separte queries to the oshdb and subsequently calculate the ratio.

Please see multiple comments at https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/147

**Comment by FabiKo117** [comment]
Maybe you should not only copy-paste the same text without any additional information to it (apart from the link). I was just starting to write (again), that it is already implemented within the ohsome API through a single request to the OSHDB 😄

**Comment by SlowMo24** [comment]
It is not possible to move issues between GitLab and GitHub ergo: "Please see multiple comments..."
If this is already implemented please merge the feature or close the issue.

**Comment by FabiKo117** [comment]
The direct moving of issues was not what I mean. I was mistaking the message of @nb152 as your message. Maybe making it more clear through adding something like "opened by @nb152 who stated: _In our last osm..._" would make it more clear to avoid such confusions ;-) <br>
As I said it is implemented in the ohsome API and not in the OSHDB. I am happy to provide any feedback and help on the transformation of the code.

**Comment by Hagellach37** [comment]
This is handled in the ohsome API.
