### ISSUE TITLE
Better mapping of Way/Relation to Cells

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#102]
opened by @tyrasd 

Currently, the bounding box will be calculated according to the bounding boxes for all of his nodes(over the complete history). This could lead to big bounding boxes for a way. 
for example if a node before or after the lifespan of the way is used in an other location.

Better: calculate the boundingbox only for the lifespan of the way/relation.

see https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/8

**Comment by Hagellach37** [comment]
This would be a minimal optimization. We consider it out of scope for OSHDB.
