### ISSUE TITLE
Implement ZGrid

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#114]
ZGrid is preferred over XYGrid. This needs to be fully implemented to replace it.
See 
https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/67
https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/tree/transitionToNewIndex

**Comment by Hagellach37** [comment]
Out of scope for OSHDB.
