### ISSUE TITLE
ETL-Load deletes data if not persisted

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#117]
https://github.com/GIScience/oshdb/blob/master/oshdb-tool/etl/src/main/java/org/heigit/bigspatialdata/oshdb/tool/importer/util/OSHDB2Ignite.java#L65
Turning the cluster off and on causes loss of non persisted data. This should be solved because persistence is not always necessary/desired and slows down import.

**Comment by SlowMo24** [comment]
related: #116 -> persistence had to be used although not needed.

**Comment by rtroilo** [comment]
this issue is closed by commit 2b96e1ca188c2de641861d81c7df8fe412fdf790
