### ISSUE TITLE
OSHDBGeometryBuilder - timestamp before first appearance

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#118]
**timestamp before first appearance**  
[Test 1](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmhistorytestdata/OSHDBGeometryBuilderTestOsmHistoryTestDataNodesTest.java) [testdata](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/resources/different-timestamps/node.osm): A single node, lat lon changed.  
Trying to get coordinates before first timestamp fails:   
java.lang.AssertionError: cannot produce geometry of entity for timestamp before this entity's version's timestamp

**Comment by tyrasd** [comment]
this is supposed to throw an exception, because it's not a valid call to these methods.
