### ISSUE TITLE
OSHDBGeometryBuilder - Multipolygon with two outer rings and two inner rings touching in two nodes

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#123]
* [x] [Test 777](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/777)
* ~~[Test 778](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/778)~~
* [x] [Test 779](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/779)

![image1](https://user-images.githubusercontent.com/30441792/54130511-ccf0a800-4410-11e9-8982-5d7aab3e7efb.png)

[code for these tests](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
I believe 778 is not really a valid test case.

According to https://wiki.openstreetmap.org/wiki/Relation:multipolygon: “[inner ways make] up the optional inner ring(s) delimiting the excluded holes that must be fully inside the area delimited by outer ring(s).”

For overlapping inner rings (such as it is the case here), it is not defined if the geometry building algorithm should use the even-odd rule, the non-zero-winding rule, a subtractive algorithm or something else.
