### ISSUE TITLE
OSHDBGeometryBuilder - Multipolygon with two outer rings touching in two nodes

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#124]
* [x] ~~[Test 774](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/774)~~
![image2](https://user-images.githubusercontent.com/30441792/54131708-307bd500-4413-11e9-9f71-156c75095344.png)

* [ ] [Test 775](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/775)
![image3](https://user-images.githubusercontent.com/30441792/54131716-340f5c00-4413-11e9-88c3-0e4a75d20eee.png)

* [ ] [Test 776](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/776)

[code for tests](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
not really valid cases of osm data
