### ISSUE TITLE
OSHDBGeometryBuilder - way going back on itself

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#125]
[Test 767](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/767): The result shoule be an instance of MultiPolygon, but is not.
![image4](https://user-images.githubusercontent.com/30441792/54131919-9b2d1080-4413-11e9-8ed0-5b9595aa48c1.png)

[code for test](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
this is basically the same as #126
