### ISSUE TITLE
OSHDBGeometryBuilder - outer or inner ring that should be split into two components

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#126]
* [ ] [Test 765](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/765): The result should be an instance of Multipolygon, but is not.
![image5](https://user-images.githubusercontent.com/30441792/54132200-168ec200-4414-11e9-8311-356712608817.png)

* [ ] [Test 766](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/765): The result is not a valid OGC polygon, and has only 1 inner ring instead of expected 2.
![image6](https://user-images.githubusercontent.com/30441792/54132213-1abadf80-4414-11e9-8573-600f8453993f.png)

[code for tests](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
these are basically the same as #125

**Comment by tyrasd** [comment]
not really valid cases of osm data
