### ISSUE TITLE
OSHDBGeometryBuilder - touching outer rings

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#127]
[Test 762](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/762): The result is not an instance of a Polygon (but MultiPolygon), it is expected to be one Polygon with an inner ring (perhaps the expected result given is wrong)
![image7](https://user-images.githubusercontent.com/30441792/54132358-63729880-4414-11e9-994c-f4672aac14ee.png)

[code](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
not really valid cases of osm data
