### ISSUE TITLE
OSHDBGeometryBuilder - outer ring going back on itself

### ISSUE THREAD

**Issue by kathap** [GIScience/oshdb#128]
* [ ] [Test 759](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/759)

![image8](https://user-images.githubusercontent.com/30441792/54132690-f6abce00-4414-11e9-943b-6fa68b1fac55.png)

* [x] [Test 760](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/760)
* [ ] [Test 761](https://github.com/osmcode/osm-testdata/tree/master/grid/data/7/761)

![image9](https://user-images.githubusercontent.com/30441792/54132697-f90e2800-4414-11e9-8f41-13fdba297514.png)

[coed for these tests](https://github.com/GIScience/oshdb/blob/osm-history-testdata/oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/geometry/osmtestdata/OSHDBGeometryBuilderTestOsmTestData7xxTest.java)

**Comment by tyrasd** [comment]
not really valid cases of osm data
