### ISSUE TITLE
add support for deprecated (boundary) multipolygon tagging

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#134]
[TIL](https://github.com/openstreetmap/osm2pgsql/issues/678#issue-203310567) that one also could have used `enclave`/`exclave` as roles on boundary multipolygons. We should add support for them as well when dealing with old data.

Btw: on a more general note: It might be kind of a good idea to start thinking about how to document changes of OSM's tagging system. There would be different cases: a) stuff that used to be mapped differently – for example with another tag – in the past, like [`highway=ford`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dford) is now `ford=yes`, b) stuff that used to be mapped more coarsly and has got an improved tagging scheme (e.g. some of the [`power`](https://wiki.openstreetmap.org/wiki/Tag:power%3Dsub_station#A_note_about_retagging) stuff).

see https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/46

**Comment by Hagellach37** [comment]
This is out of scope for OSHDB, but could be added to the tag interpreter.
