### ISSUE TITLE
Improve ErrorMassage on null-object in MapReducer

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#159]
**Problem**
A hard to decipher `NullPointerException` is thrown if the return-element of the map-step of a MapReducer is null and `.uniq()` is called. 

**Favorite solution**
`null`-objects should simply be possible as a result, also for uniq().

**Alternatives**
The error-message should be improved and the javadoc of `map` as well as `uniq` should be updated, to inform users to not generate null-values.

**Comment by tyrasd** [comment]
do you have a few lines of code at hand that trigger the null pointer exception?

**Comment by tyrasd** [comment]
a slightly off topic, but related general advice: please try to simply avoid using the `null` construct (not only) in java. If you need a special "thing" to represent "missing data" (or something similar), consider the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern#Java) instead.
