### ISSUE TITLE
improve logging

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#164]
**Problem**
OSHDB chose slf4j as abstraction-layer with simple-logger as default framework for logging.

Currently the following error-message is displayed when initializing an `OSHDBIgnite`:
```
Apr 25, 2019 10:21:50 AM java.util.logging.LogManager$RootLogger log
WARNUNG: Failed to resolve default logging config file: config/java.util.logging.properties
```
because Ignite logs with java.util as default. Logs are therefore also not captured by our default logger.

Also clients get no notification on logs on the server (e.g. failures).

**Possible solution**
Clients should be started with slf4j as described in the [ignite-docs](https://apacheignite.readme.io/docs/logging).

Clients should also get logs from servers, at least failures. Therefore possibly [event subscription](https://apacheignite.readme.io/docs/events) would have to be implemented (like for #105 ).

**Comment by Hagellach37** [comment]
The current solution is "good enough" from our point of view. Out of scope for OSHDB.
