### ISSUE TITLE
Improve Javadoc of MapReducer aggregateByGeometry

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#165]
**Problem**
Inexperienced users will not know how to solve their request when running into 
```
java.lang.UnsupportedOperationException: aggregateByGeometry() cannot be used together with the groupByEntity() functionality
	at org.heigit.bigspatialdata.oshdb.api.mapreducer.MapReducer.aggregateByGeometry(MapReducer.java:862)
```
The Javadoc does state that this is impossible but fails to propose a workaround (is normal aggregateBy possible, do I have to use a map-step?)

**Solution**
Add workaround-description to javadoc and maybe even to error-message.

**Alternative**
Implement the workaround as default behaviour and notify the user, that this has to be used with caution.

**Comment by SlowMo24** [comment]
here is my workaround:
```
Map<Integer, Integer> result = OSMContributionView
        .on(oshdb)
        .keytables(keytables)
        .areaOfInterest(bb)
        .areaOfInterest((Polygon) aoi)
        .timestamps(ts)
        .groupByEntity()
        .map(list -> {
          Map<Integer, Integer> map = new HashMap<>(1);
          list.forEach(contrib -> {
            Geometry geometry;
            if (contrib.getContributionTypes().contains(ContributionType.DELETION)) {
              geometry = contrib.getGeometryBefore();
            } else {
              geometry = contrib.getGeometryAfter();
            }
            geoms.forEach((id, geomb) -> {
              if (geomb.intersects(geometry)) {
                map.put(id, 1);
              }
            });
          });
          return map;
        })
        .reduce(
            () -> new HashMap<Integer, Integer>(),
            (Map<Integer, Integer> map1, Map<Integer, Integer> map2) -> {
          HashMap<Integer, Integer> hashMap = new HashMap<>();
          hashMap.putAll(map1);
          map2.forEach((geo, num) -> {
            hashMap.merge(geo, num, (a, b) -> a + b);
          });
          return hashMap;
        });
```

**Comment by tyrasd** [comment]
well, I would prefer to improve the implementation to not even need a workaround. :) I don't believe that having a workaround code in a javadoc is a good practice (it can break easily, can't be unit-tested, get's overlooked, etc.).

So, here's how we could make it better: I believe it wouldn't be too hard to add a second `aggregateByGeometry` method that not only accepts the map of geometries but also a function that returns a "feature" geometry (like the first half of the map function in your workaround example). Then one could use the aggregateByGeometry functionality also in even more use cases, e.g. where the geometry needs to be modified before the aggregate step (e.g. computing a buffer around a snapshot geometry, or calculating the mean centroid of all contributions happening on a single osm entity, etc.).

**Comment by tyrasd** [comment]
-> #290
