### ISSUE TITLE
Individual extracts

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#166]
**Problem**
One might need a specific extract from the OSHDB to run locally. For geographic extracts, this is rather straight foreward using osmium and creating a personal extract. But other use-cases (e.g. all entities ever touched by a set of users) requires some computing power on the global dump.

**Possible Solution**
Analogous to the `ContributionView` one could think of an `ExtractionView` where filters can be set as known and a local h2-file is created.

**Alternative**
Leave it to the user as explained above.

**Comment by tyrasd** [comment]
this is implemented in an external tool: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/oshdb-extractor
