### ISSUE TITLE
Wrong area computation of Multipolygons with holes

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/oshdb#171]
**Describe the bug**
The area of a relation is too high.

**To Reproduce**
relation: https://www.openstreetmap.org/relation/5608072/
request to the ohsome API: https://api.ohsome.org/v0.9/elements/area?bboxes=8.688308,49.401807,8.690003,49.403273&format=json&keys=building&time=2019-04-01&types=relation&values=hospital
ohsome API value: 6448.93

**Expected behavior**
To compute correct(ish) results:
geojson.io: 5399.27
geometry from ohsome API in QGIS: 5393.5

**System (please complete the following information):**
browser: chrome Version 74.0.3729.131 (Official Build) (64-bit) on Windows

**Comment by tyrasd** [comment]
offending code: https://github.com/GIScience/oshdb/commit/155cfa3cfa63a5dc908c2c0ab5cb0b9c0177045c
