### ISSUE TITLE
API-tutorial: wrong base class use for keytables

### ISSUE THREAD

**Issue by sfendrich** [GIScience/oshdb#18]
Following the [API-tutorial](https://github.com/GIScience/oshdb/blob/master/documentation/oshdb-api-tutorial/mandatory-settings.md) I get the following compilation error when trying to inlcude key-tables:

"The method keytables(OSHDBJdbc) in the type MapReducer<OSMEntitySnapshot> is not applicable for the arguments (OSHDBDatabase)"

A previous version of the tutorial used `OSHDB_JDBC tagsDB = new [...]` which is now replaced by `OSHDBDatabase tagsDB = [...]`. Switching back to the (now renamed) `OSHDBJdbc tagsDB = new [...]` does ~~not~~ solve the problem.

**Comment by tyrasd** [comment]
Maybe we should get rid of that section from the (beginners) tutorial, since keytables are normally included in [downloaded](http://downloads.ohsome.org/v0.4/) oshdb files? It could be mentioned in a (still to be written) more advanced tutorial.

**Comment by SlowMo24** [comment]
is now part of #139
