### ISSUE TITLE
Remove references to artifactory

### ISSUE THREAD

**Issue by joker234** [GIScience/oshdb#182]
All public releases should be available in the central repository, starting with the next release (see #181). Documentation should be changed with the release to remove the additional heigit release repository. If changed earlier, people would think this is already the case for the current release.

One example is:
https://github.com/GIScience/oshdb/blob/540ee31ae78f8425f4cd65d02474c85dcdf65832/documentation/first-steps/README.md#L32-L41

**Comment by SlowMo24** [comment]
off topic: can we get an image-icon here: https://mvnrepository.com/search?q=oshdb
?

**Comment by joker234** [comment]
> off topic: can we get an image-icon here: https://mvnrepository.com/search?q=oshdb
> ?

I think this is a custom icon choice by the websites maintainer. I ask him if its possible to get icons to custom domains. I only saw icons using `com.github`, `io.dropwizard`, and `org.apache.maven`.
