### ISSUE TITLE
Update documentation on repository

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#184]
OSHDB is now deployed to Maven central. We might therefore update the documentation an changelog to infor new and old users. Also access to [artifactory](http://repo.heigit.org/) might be restricted as it is only used internally for snapshots (and by ORS).

**Comment by tyrasd** [comment]
> Also access to artifactory might be restricted as it is only used internally for snapshots

why should snapshots not be publicly available?

**Comment by tyrasd** [comment]
is this ticket not the same as #182 ?

**Comment by SlowMo24** [comment]
> is this ticket not the same as #182 ?

you are right it is. Overlooked

**Comment by SlowMo24** [comment]
> > Also access to artifactory might be restricted as it is only used internally for snapshots
> 
> why should snapshots not be publicly available?

They should, but http://repo.heigit.org/artifactory/webapp/#/artifacts/browse/tree/General/main maybe should not.
