### ISSUE TITLE
Update TagTranslator via Postgres Listen

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#186]
**Problem**
Tagtranslators are not updated automatically if the Keytables are updated. Using the Updater #38 may cause problems on long running TagTranslators.

**PossibleSolution**
Subscribe TagTranslators to PostGres Notification mechanism. See e.g.

https://jdbc.postgresql.org/documentation/81/listennotify.html
https://tapoueh.org/blog/2018/07/postgresql-listen/notify/#listen-and-notify
https://www.postgresql.org/docs/10/logical-replication.html

**Comment by Hagellach37** [comment]
This will be addressed in the new TagTranslator.
