### ISSUE TITLE
Refactor CellIterator to accept OSHEntity-Stream

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#187]
Currently the [CellIterator](https://github.com/GIScience/oshdb/blob/master/oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/celliterator/CellIterator.java#L182) accepts GridOSHEntities as input to perform checks and return a Stream of OSHEntites. This could be split inito seperate methods to allow other functions to use this Class with an existing OSHEntity-Stream. This would reduce a lot of code and computation for the updater: https://github.com/GIScience/oshdb/blob/updater/oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java#L1991

//cc @rtroilo

**Comment by Hagellach37** [comment]
This feature already exists.
