### ISSUE TITLE
Request deleted objects

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#188]
**Problem**
In some use-cases the information on deleted objects is valuable. The `OSMEntitySnapshotView` does not provide objects that were deleted but had their last location in the requested area.

**Solution**
Add an option to display deleted objects also.

**Alternative**
Create a view on deleted objects only.

//cc @tyrasd

**Comment by Hagellach37** [comment]
You can use the contributionView for this.

**Comment by SlowMo24** [comment]
see here for code on how to do this: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/deleted_map
