### ISSUE TITLE
Member way of Relation is null

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#190]
**Describe the bug**
In a not so recent oshdb-h2-file of BW Relation 2070994 has Way 12605199 as member but `.getEntity()` returns null.

How can this be?

**To Reproduce**

```
OSMMember[] members = ((OSMRelation) ent).getMembers();
mem[0].getEntity();
```
**Expected behavior**
Return an OSH-Entity

**Error messages, logs, screenshots**
none
**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: openjdk version "1.8.0_191"
 - OSHDB Version 0.5.1
 - Maven version  3.3.2

**Additional context**
I may provide the timestamp for the OSMRelation if necessary.

**Comment by rtroilo** [comment]
Hi Moritz, 
yes it is possible that the member of a way is null. The most common reason is in extracts like BW we use osmium with extract strategy "complete-ways" to cut out the region first and create the oshdb from this extract.
Look at [osmium-tool](https://osmcode.org/osmium-tool/manual.html#creating-geographic-extracts)

A other possible null member could be if the way or even node is invalid, in sense that it has never be a valid coordinate, very very rare case.

**Comment by SlowMo24** [comment]
Thanks for the answer. Considering that we have the full history, could we not fill up the first case with the entities from our dataset?

**Comment by rtroilo** [comment]
You talk about the second case, right? With invalid way/nodes which never have a valid coordinate!
The answer is No :-), still with our full history, there are (very very rare cases),  nodes which we can not reconstruct, and even ways.

For the first case, we could do an oshdb extract not base on an extract from the osm-planet full, but from our global oshdb, that this case the member entity of a relation should not be null.
