### ISSUE TITLE
flatMap + aggregate by destroys reduce-procedure

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#195]
**Describe the bug**
I use a flatMap()-step on contributions grouped by Entity followed by three aggregateBy() statements followed by a reduce(identitySupplier,accumulator,combiner). 

All three functions in the reduce-step are pure.

While the accumulator works normally, the combiner only receives accumulator-results for the last entry in the list returned by the flatMap().

**To Reproduce**
Pseudocode on a `MapReducer<OSMContribution>`  :
```
 ...
        .groupByEntity()
        .flatMap(x -> {
          List<int[]> result = new ArrayList<>();
          result.add(new int[]{0, 0, 1});
          result.add(new int[]{0, 1, 0});
          return result;
        })
        .aggregateBy(inti -> inti[0])
        .reduce(() -> new Result(),
            (Result a, int[] b) -> {
          Result c = new Result();
//edit
          c.y = a.y + b[1];
          c.z = a.z + b[2];
          return result;
        },
            (Result a, Result b) -> {
          Result c = new Result();
          c.y = a.y + b.y;
          c.z = a.z + b.z;
          return result;
        })
```
will return result.y=n and result.z=0 while both should be n. If we flip the order of adding to the List we get the inverse.

**Comment by sfendrich** [comment]
Without any context, the code is difficult to read.
Is "Result" a vector with three components x, y and z? Is it initialized to {0,0,0} when calling "Result()"?
If so, then I understand the code as follows:

- flatMap returns a list of the shape [{0,0,1},{0,1,0},{0,0,1},{0,1,0}, ...] (2*n entries)
- aggregateBy aggregates by x-component which is always 0, so we only have one aggregation set.
- In the accumulator b[0] is always 0, so c.y sums up to 0 in the end; b[1] is 0 resp. 1 in half of the cases, so c.z sums up to n
- The combiner just sums up the components

Hence, I would expect result.y = 0, and result.z = n.

**Comment by rtroilo** [comment]
`c.y = a.y + b[0];
 c.z = a.z + b[1];
`
I also expect result.y=0 and result.z=n

**Comment by SlowMo24** [comment]
I'm sorry. the code is hard to read (I was in a hurry) and wrong indeed!
But I have to apologise for wasting your time, the bug was of course in my code. I failed to preserve all attributes of Result a in the accumulator when checking on a certain property of int[] b.
