### ISSUE TITLE
GIS Science link on https://ohsome.org/apps/osm-history-explorer/ is broken

### ISSUE THREAD

**Issue by rossbernet** [GIScience/oshdb#212]
**Describe the bug**
The Link to GIS Science in the top right of this screenshot on this [page](https://ohsome.org/apps/osm-history-explorer/):
![image](https://user-images.githubusercontent.com/8103418/73560525-239a1280-4425-11ea-97bd-3e320192f52b.png)

takes me here:
https://giscience.uni-heidelberg.de/

Which does not seem to work.

**Comment by tyrasd** [comment]
Thanks for noticing! :smiley: It will be fixed with a larger update of the website planned for this week.
