### ISSUE TITLE
get rid of global keytables

### ISSUE THREAD

**Issue by tyrasd** [GIScience/oshdb#225]
Our current global keytables approach has many downsides: they are bulky, slow, unintuitive and cause headaches when implementing code that needs to be executed on a distributed system (because contrary to the rest of the data, the keytables are actually _not_ distributed).

Maybe a better way to solve the compression of OSM tags would be to get rid of the whole concept of separate global keytables altogether. I would prefer to try a solution with small local string tables, as it is solved in other state of the art OSM data schemas. For example like the `StringTable` in an [osm-pbf data block](https://wiki.openstreetmap.org/wiki/PBF_Format#Definition_of_OSMData_fileblock), or like the attributes in [MVT](https://docs.mapbox.com/vector-tiles/specification/#encoding-attributes). I believe [Apache ORC](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+ORC#LanguageManualORC-StringColumnSerialization) does something similar with strings.

**Comment by Hagellach37** [comment]
not planned for now.
