### ISSUE TITLE
Where are the code and doc of Dashboard ?

### ISSUE THREAD

**Issue by pyrog** [GIScience/oshdb#255]
All is in the title 😃

**Comment by tyrasd** [comment]
The dashboard's code is not (yet) on github, I'm afraid. There's also no dedicated documentation, it should be pretty self-explanatory, though. What exists is the code and documentation of the API which is the main "brain" behind the dashboard: See https://github.com/giscience/ohsome-api and https://docs.ohsome.org/ohsome-api/stable/
Would you like to adapt the dashboard for something specific, or report a bug, or something else?

**Comment by pyrog** [comment]
I discovered the `,` separator for `Grouping Keys` after several trials.
A placeholder in this field or a hint could help 😃

Publishing the dashboard code could help to understand it, report a bug, or yes, adapt it for another project.

**Comment by tyrasd** [comment]
The dashboard is now finally on github: https://github.com/GIScience/ohsome-dashboard. :tada:
