### ISSUE TITLE
Timestamp 2010-01-01T00:00Z throws Date or DateTime Format not supported

### ISSUE THREAD

**Issue by rtroilo** [GIScience/oshdb#259]
**Describe the bug**
Trying to use the timestamp 2010-01-01T00:00Z as a start timestamp for the oshdb-api throws an 
```java
..
.timestamps("2010-01-01T00:00Z", "2020-01-01-T:00:00Z")
.count();
```
[main] ERROR org.heigit.bigspatialdata.oshdb.api.mapreducer.MapReducer - unable to parse ISO date string: Date or DateTime Format not supported: 2010-01-01T00:00Z

**Comment by rtroilo** [comment]
same is true for 

2010-01-01T00Z

**Comment by tyrasd** [comment]
the relevant code should be around here: https://github.com/GIScience/oshdb/blob/master/oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java#L66-L75

**Comment by tyrasd** [comment]
@mcauer would you like to take a look at this one?
