### ISSUE TITLE
OSHEntity Filter

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#274]
Currently to get non-region-related contribution information (user specific (#170 ), changeset specific, object specific etc.) creates a large overhead of contribution objects, that are then only later filtered in the MapReduce-pipeline. Implementing `GridOSHEntity`and `OSHEntity`filters would reduce computation and memory cost for e.g. user or object based analyses, especially when the area of interest is large.

Would partly address #254 .

**Comment by tyrasd** [comment]
I think #253 would solve this, actually, at least to some extent: It provides a more flexible method to inject more complex filters than what is currently possible (and IMHO a more elegant interface than to just provide more use-case specific filter methods): [`MapReducer::filter(FilterExpression f)`](https://github.com/GIScience/oshdb/pull/253/files#diff-a0f56b913e00c48bcbd8a56acd74afe1adf7d9115b8aabf816bfa967f3be3d5dR717-R728) allows to supply a [filter expression](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/ohsome-filter/-/blob/1.3/src/main/java/org/heigit/ohsome/filter/FilterExpression.java) object. It was meant to be used primarily with the _ohsome filter_ library, but can be used standalone as well:

```java
  ….filter(new Filter() {
      @Override
      public boolean applyOSM(OSMEntity entity) {
        return true;
      }

      @Override
      public boolean applyOSH(OSHEntity entity) {
        return setOfAllowedIds.contains(entity.getId());
      }

      @Override
      public FilterExpression negate() {
        return null;
      }
    });
```

**Comment by SlowMo24** [comment]
This sounds great :tada: and #253 seems nearly finished (judging by the checkboxes). When will it get merged?

**Comment by tyrasd** [comment]
> When will it get merged?

when ohsome-filter v1.4 is ready and published. could be soon

**Comment by rtroilo** [comment]
this is great!
