### ISSUE TITLE
add aggregateByGeometry method with callback function

### ISSUE THREAD

**Issue by tyrasd** [GIScience/oshdb#290]
from https://github.com/GIScience/oshdb/issues/165#issuecomment-487129692:

> I believe it wouldn't be too hard to add a second `aggregateByGeometry` method that not only accepts the map of geometries but also a function that returns a "feature" geometry. Then one could use the `aggregateByGeometry` functionality also in even more use cases, e.g. where the geometry needs to be modified before the aggregate step (e.g. computing a buffer around a snapshot geometry, or calculating the mean centroid of all contributions happening on a single osm entity, etc.).

**Comment by Hagellach37** [comment]
This can be implemented by the client. Out of scope for OSHDB for now.
