### ISSUE TITLE
integrate "ohsome filter" library (as oshdb-filter module), deprecate "old" filters

### ISSUE THREAD

**Issue by tyrasd** [GIScience/oshdb#302]
see corresponding [gitlab issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/ohsome-filter/-/issues/15).

* [x] import code as new module (`oshdb-filter`) in this repository
* [x] deprecate `osmTag`, `osmType` filters
* [x] update documentation, examples, benchmarks
  * [x] rename ohsome filter to oshdb filter https://github.com/GIScience/oshdb/blob/66c04e5f1d440d2e79a393682ec2b9354d62319c/documentation/manual/filters.md#L47
  * [x] replace GitLab link https://github.com/GIScience/oshdb/blob/66c04e5f1d440d2e79a393682ec2b9354d62319c/documentation/manual/filters.md#L50

**Comment by joker234** [comment]
I think it's easier to merge #304 first.
