### ISSUE TITLE
Query/aggregate by OSM user ID?

### ISSUE THREAD

**Issue by Guiming** [GIScience/oshdb#349]
### Problem Description
I'd like to obtain some user-specific contribution statistics from OSM history. Is it possible to achieve this using current oshdb features? According to the [documentation](https://github.com/GIScience/oshdb/blob/master/documentation/manual/views.md), with Contribution View, one has access to the ID of the OSM user who performed this contribution. So I assume it is feasible to query/aggregate by user ID, but I did not find this feature in the [filters ](https://github.com/GIScience/oshdb/blob/master/documentation/manual/filters.md)or [aggregation](https://github.com/GIScience/oshdb/blob/master/documentation/manual/aggregation.md).

### Expected Solution
Allow to query/aggregate by OSM user ID with the Contribution View.

**Comment by rtroilo** [comment]
Hi @Guiming,
sure both, filtering and aggregation for userId is possible.
here a quick example:
```java
 var userOfInterest = Set.of(123, 456, 789);
 
 var result = contribView
   .areaOfInterest(areaOfInterest)
   .timestamps(beginTs, endTs)
   // for syntax see: https://github.com/GIScience/oshdb/tree/master/oshdb-filter
   .filter("building=* or highway=*")
   // here you can filter on contribution users
   .filter(contrib -> userOfInterest.contains(contrib.getContributorUserId()))
   // https://github.com/GIScience/oshdb/blob/docu-update-cleanup/documentation/manual/aggregation.md#aggregateby
   .aggregateBy(contrib -> contrib.getContributorUserId())
   .count();
 
 // result = SortedMap<Integer, Integer>
 result.forEach((uid, count) -> System.out.printf("%4d - %4d%n", uid, count));  
```

be aware, it is easy to over count users contributions depending on your definition of a contribution.
for an example, if a user moves a osm-node which belongs to multiple osm-way segments, let's say the osm-node of a street junction, than you will get a contribution for every osm-way which were affected plus the contribution of the moving node it self.
