### ISSUE TITLE
reduce impact of JTS topology exceptions

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#351]
If an area-of-interest polygon is given that touches a (polygonal) OSM feature that is to be returned, it sometimes causes the OSM feature to be missing in the result (see https://github.com/GIScience/ohsome-api/issues/122).

see https://github.com/GIScience/ohsome-api/issues/122 for more information

**Comment by tyrasd** [comment]
to summarize and clarify the bug further:

* likely "something" caused a topology exception in JTS; potentially while performing a _intersection_ check
* the OSHDB API catches the exception, and ignores silently ignores the "feature" in the result

We should now:

* [ ] investigate where exactly these topology exception occur
* [ ] what can be done to minimize their impact on query result
* [ ] check if upgrading to a newer version of JTS helps [fixing these issues](https://lin-ear-th-inking.blogspot.com/2020/10/overlayng-lands-in-jts-master.html)

**Comment by Hagellach37** [comment]
We upgraded to a newer version of JTS. Out of scope for OSHDB for now.
