### ISSUE TITLE
fix OSM data with broken geometry within OSHDB?

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/oshdb#367]
### Problem Description
Some OSM features have a broken geometry and can therefore not be properly displayed when feeding the response directly into e.g. a GIS.

### Expected Solution
Return a fixed geometry for those features.

### Alternative Solutions
Just continue with the status-quo, meaning that the OSHDB does not perform any fixing on broken OSM features.

### Additional Context
Out of a recent discussion in https://github.com/GIScience/ohsome-api/issues/55 @SlowMo24 raised the idea of returning e.g. a proper geometry for potentially broken OSM features through the OSHDB.

**Comment by SlowMo24** [comment]
Returning invalid geometries is valuable e.g. for quality assessment. Returning cleaned geometries should therefore only be an OPTION. Also it should be clearly stated what happens if no correct geometry can be generated.

**Comment by tyrasd** [comment]
you can already do this by just mapping any invalid geometry with your preferred geometry-fixing routine of choice. For example:

```java
OSMEntitySnapshotView.on(…).…
    .map(snapshot -> snapshot.getGeometry())
    .map(geom -> {
      if (!geom.isValid()) {
        return geom.buffer(0);
      } else {
        return geom;
      }
    })
    .…
```

**Comment by SlowMo24** [comment]
how does this help ohsome users? I think this issue is in the wrong project. The idea (more: the question, if there is a user group for this feature) was to provide cleaned geometries for the (extraction) endpoints of ohsome (see https://github.com/GIScience/ohsome-api/issues/55).

**Comment by tyrasd** [comment]
> how does this help ohsome users?

arm, are you referring to users of the ohsome API? then you are indeed in the wrong repository: this is about the OSHDB here. :sunglasses:

**Comment by SlowMo24** [comment]
wan't me :-) @FabiKo117

**Comment by FabiKo117** [comment]
What speaks against adding this functionality then e.g. as a callable method to the `MapReducer` for example?
I personally would see such a feature, meaning OSM geometry manipulation, in the OSHDB(API) and not in the closer-to-the-enduser ohsome API, hence I moved this discussion here.

**Comment by tyrasd** [comment]
because a) there is no single algorithm to make invalid geometries valid, and b) this would be a poor design pattern: why only include "`fixInvalid`" as a built-in geometry operation – why not also add `buffer`, intersecting, reprojecting, and what-else-do-you-have to the API? The amount of code to be maintained would blow up pretty quickly for literally no added benefit. :shrug: What's the problem with using a single `map` function for this?

**Comment by FabiKo117** [comment]
Then just call it `geometry cleaning` as you did above, I don't care much about the wording, but more about what is possible and where to put that of course :)

> The amount of code to be maintained would blow up pretty quickly

Well yeah, that's basically what happened in the ohsome API :D I still remember Sascha's surprised reaction when he saw how much code there already was in the ohsome API back in 2018 when he made a code review of selected classes. But anyway, it developed now into that state and sure, we can just continue going that road.
