### ISSUE TITLE
Add deprecated methods to version update changelog table

### ISSUE THREAD

**Issue by joker234** [GIScience/oshdb#405]
e.g. deprecation of `getRawTags()` with explanation, that this is no longer supported and should be replaced by `getTags()`. Same for `getRawTagKeys()`

**Comment by tyrasd** [comment]
IMHO these methods were never meant to be used directly by end users, and were never really documented (neither in the written docs nor javadoc AFAICS). So, maybe it's not necessary to provide upgrade paths for these in the changelog?
