### ISSUE TITLE
contributor filter with additional other filter does not work correctly.

### ISSUE THREAD

**Issue by rtroilo** [GIScience/oshdb#409]
### Bug Description
When filtering for contributors with additional other filters does not work correctly.

```java

var filter = "contributor:1822133 " 
    + "and type:node"; // with this additional filter

var result = OSMContributionView.on(oshdb).keytables(keytables)
    .areaOfInterest(bboxWgs84Coordinates(-180, -90, 180, 90))
    .filter(filter)
    .aggregateBy(OSMContribution::getContributorUserId)
    .count();

assertEquals(1, result.size());
```

reported by @SlowMo24

**Comment by SlowMo24** [comment]
This may be unrelated and I will file a different bug in that case but something tells me that the following behaviour goes in the same direction:

Requesting one building tag grouped by building key works fine:

`curl -X POST "https://api.ohsome.org/v1/elements/area/groupBy/tag" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "bboxes=7.614272368193529%2C48.65702077458387%2C9.13521359578018%2C49.65272281436074&filter=building%3Dresidential&format=json&groupByKey=building&time=2021-06-13T10%3A25%3A59"`

```
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.5.0",
  "groupByResult": [
    {
      "groupByObject": "building=residential",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 11989738.62
        }
      ]
    }
  ]
}
```

requesting residential buildings grouped by natural key also works fine:

`curl -X POST "https://api.ohsome.org/v1/elements/area/groupBy/tag" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "bboxes=7.614272368193529%2C48.65702077458387%2C9.13521359578018%2C49.65272281436074&filter=building%3Dresidential&format=json&groupByKey=natural&time=2021-06-13T10%3A25%3A59"`

```
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.5.0",
  "groupByResult": [
    {
      "groupByObject": "remainder",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 11989738.62
        }
      ]
    }
  ]
}
```

but requesting residential and other buildings grouped by natural key returns a strange result

`curl -X POST "https://api.ohsome.org/v1/elements/area/groupBy/tag" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "bboxes=7.614272368193529%2C48.65702077458387%2C9.13521359578018%2C49.65272281436074&filter=building%3Dresidential%20or%20building%3Dyes&format=json&groupByKey=natural&time=2021-06-13T10%3A25%3A59"`

```
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.5.0",
  "groupByResult": [
    {
      "groupByObject": "remainder",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 237458958.23
        }
      ]
    },
    {
      "groupByObject": "natural=water",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 6162.25
        }
      ]
    },
    {
      "groupByObject": "natural=bare_rock",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 1177.67
        }
      ]
    },
    {
      "groupByObject": "natural=spring",
      "result": [
        {
          "timestamp": "2021-06-13T10:25:59Z",
          "value": 30.24
        }
      ]
    }
  ]
}
```

**Comment by tyrasd** [comment]
> returns a strange result

you mean strange in the sense of that you did not expect entries like `natural=spring` in the result? There are some OSM objects like [this one](https://www.openstreetmap.org/way/536219257) which do [have both tags](https://overpass-turbo.eu/s/19T4), which explains the results. Or did you mean something else?

**Comment by SlowMo24** [comment]
yes, unexpected is what I meant and thank you for the example. I first thought of these 'double' objects but dropped that thought when I saw the natural=bare_rock. Seems like I was wrong and should dig deeper into the data. Yet the result is still unexpected but maybe reasonable and probably hard to prevent.

**Comment by tyrasd** [comment]
here's the object with bare_rock: https://www.openstreetmap.org/way/93066394 :european_castle:
