### ISSUE TITLE
TagTranslator returns Null if OSMTag is unknown

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#498]
### Bug Description

`TagTranslator.lookupTag(OSHDBTag)` returns `Null` if the `OHSDBTag` cannot be found.

This is confusing because

- the documentation states that ` @throws OSHDBTagOrRoleNotFoundException if the given tag cannot be found` . There are only some functions that throw this exception.
- all `getOSHDB...` return an optional while all `lookup..` methods return an object. 

The behaviour of `TagTranslator` may need to be streamlined.

**Comment by rtroilo** [comment]
> TagTranslator.lookupTag(OSHDBTag) returns Null if the OSHDBTag cannot be found.

This is the intended behavior. A lookup have to always return a not null `OSMTag` otherwise (NULL) would indicate an false state of the keytables/oshdb!

PR #503 removes therefor the wrong/left-over documentation of a previously thrown `OSHDBTagOrRoleNotFoundException`

**Comment by SlowMo24** [comment]
> otherwise (NULL) would indicate an false state of the keytables/oshdb!

this should be documented in the javadoc

> OSHDB -> OSM have to be always a result otherwise the database is in an invalid state

I came to this point when adding a dummy OSHDBTag during processing on the cluster (i.e. when processing failed). The question is, if an invalid state of the db is something that should be silently ignored (NULL) or actively communicated to the users (Optional or Exception)?
