### ISSUE TITLE
First steps data extract not available

### ISSUE THREAD

**Issue by Robot8A** [GIScience/oshdb#519]
### Bug Description
In the [First Steps documentation](https://github.com/GIScience/oshdb/blob/master/documentation/first-steps/README.md), a link to download an OSHDB extract from the download server exists. However, that link returns 403.

### How to Reproduce
Steps to reproduce the behaviour:
1. Go to https://downloads.ohsome.org/OSHDB/v1.0/
2. 403 Forbidden

### Expected behaviour
Data extract is accessible

### Further Information
Not needed

**Comment by Hagellach37** [comment]
Hey @Robot8A,
thanks for reaching out here as well. We are sorry that we are currently not providing data extracts. We will discuss this within our team, but it's not yet clear if and how quick this will be available again.

I would be curious to hear more about your OSHDB use case and for which analysis you would need a local extract. Feel free to reach out to me via ohsome@heigit.org.

**Comment by tyrasd** [comment]
Some example extracts are now available again on the downloads server (after login with an osm.org account).
