### ISSUE TITLE
Huge filter leads to unresponsive ohsome API

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/oshdb#530]
### Bug Description
Sending a request to geometry extraction endpoint with a single small bpoly but a huge filter makes the ohsome API unresponsive.

### General Information
Please include the following general information about the issue and list any additional steps needed to reproduce the bug.
 - Version of the ohsome API:  1.10.2 
 - Which API instance was requested: https://api.ohsome.org/v1
 - Affected endpoint(s): /elements/bbox
 - Used HTTP method; POST
 - Utilized tool/library for the request: ohsome-py

[bazooka_query.txt](https://github.com/user-attachments/files/15871788/bazooka_query.txt)

**Comment by tyrasd** [comment]
The problem with this (extreme) filter is that its large number of `or` boolean operators makes calculating the disjunctive normal form of the filter ([here](https://github.com/GIScience/oshdb/blob/1.2.2/oshdb-filter/src/main/java/org/heigit/ohsome/oshdb/filter/FilterExpression.java#L141-L150)) extremely inefficient. This computation is done in the _optimization_ phase before executing the query. It would be possible to implement a fail-safe which aborts this particular optimization if the DNF blows up, but as it works fine for filters of "reasonable" complexity, I think it is not really necessary at the moment.
