### ISSUE TITLE
Endless loading in OSHRelation.getModificationTimestamps()

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/oshdb#8]
When sending a simple request over the ohsome-API about bicycle routes for a small bbox in Rheinland-Pfalz (Germany), the code seems to be somehow stuck (or needs far too much time) within the OSHRelation.getModificationTimestamps() method. The reason seems to be that the relation https://www.openstreetmap.org/relation/88376#map=9/49.9658/7.3759 is quite big and has lots of versions and members with loads of different timestamps.
<p>
This is the request URI: /elements/count?time=2012-06-15&showMetadata=true&keys=route&values=bicycle&bboxes=7.6563,49.4635,7.7727,49.513&types=relation

**Comment by tyrasd** [comment]
It was not actually a bug. Just a part where the implementation was especially slow in some cases. With #10 this should be fixed.

**Comment by tyrasd** [comment]
PS: we found a related issue (using similar queries as the one above), where the internal buffering of the celliterator causes excessive memory usage, which is addressed in #20.
