### ISSUE TITLE
Make Jenkins deploy uber-jar (fat-jar, jar-with-dependencies) to artifactoy

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#80]
For easy installation of oshdb to Ignite, a jar with dependencies is useful and should be stored in artifactory repository.

**Comment by SlowMo24** [comment]
https://github.com/GIScience/oshdb/tree/jenkins-fat-jar

**Comment by SlowMo24** [comment]
#81 solves the issue with http://maven.apache.org/plugins/maven-assembly-plugin/
might also be solved using http://maven.apache.org/plugins/maven-shade-plugin/
Example output can be seen here: http://repo.heigit.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/heigit/bigspatialdata/oshdb/0.5.0-SNAPSHOT/oshdb-0.5.0-20190301.094759-258-jar-with-dependencies.jar

**Comment by tyrasd** [comment]
Thanks! Some suggestions:

* is it possible to build the jar with dependencies only for the `oshdb` core module (and not also for the other modules like oshdb-api, etl, etc.)?
* could you please move the `withDeps` profile definition over for the from the "bigspatialdata parent" pom file to the matching spot in this repository (maybe into https://github.com/GIScience/oshdb/blob/master/oshdb/pom.xml)?
* the other two profiles defined in the parent pom (complete, and deployignite) are not needed anymore, right?

**Comment by SlowMo24** [comment]
1. this could be a solution: https://stackoverflow.com/questions/3532297/how-to-activate-a-maven-profile-in-a-dependent-module
or we just run build and deploy a second time using only oshdb-module?
2. yes, sure, that profile is OLD!!!
3. yes, an never have been.

**Comment by SlowMo24** [comment]
https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/parent/commit/df21caad95c7e63cf555584ee783633e65834064
