### ISSUE TITLE
OSM-Notes

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#84]
In addition to OSM-Data, notes (with a T) are comments on the map by registered or non registered users similar to the fixme-tag. Similar to changesets (#52) they have a geographic location, text and comments.
Although their number is limited they might be interesting for future research.

useful link to load data into postgres: https://github.com/mapbox/osm-comments-parser

**Comment by SlowMo24** [comment]
- [ ] write code to retrieve Notes from planed dump
- [ ] store Notes in postgres
- [ ] create osdb-class to retrieve Note-data
- [ ] implement and import Notes to oshdb-core

**Comment by Hagellach37** [comment]
not planned at the moment
