### ISSUE TITLE
OSM-Users

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#85]
The user-name-resolver (https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/username-resolver, formerly tracked in #59) is a first step but users have more information then their name that we could store:
- [ ] names can be changed over time, currently this only returns the latest name
- [ ] users may delete their account, this info is published here: https://planet.openstreetmap.org/users_deleted/
- [ ] users may agree or disagree to the new license: https://planet.openstreetmap.org/users_agreed/

**Comment by Hagellach37** [comment]
not planned at the moment, outside the scope of OSHDB
