### ISSUE TITLE
OSM-Tile-Logs

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#86]
Similar to #84 the tile-logs (https://planet.openstreetmap.org/tile_logs/) are not directly linked to the data but might spark research.
Therefore they would be a good data set for our oshdb.
For reference:
http://lukasmartinelli.ch/python/2015/05/24/parsing-and-visualizing-osm-access-logs.html

**Comment by SlowMo24** [comment]
implementation we could import and write a wrapper class for:
https://github.com/tyrasd/osm-tile-access-log-viewer

**Comment by SlowMo24** [comment]
While usernames (#85) like the keytables are part of the core OSM-DB changesets (#52), notes (#84 ) and tile-logs are more of a meta structure. We might therefore think of moving them into a plugin-repository?

**Comment by tyrasd** [comment]
not a priority at the moment.
