### ISSUE TITLE
Solve FindBugs Warnings

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#91]
see #90 
- [ ] etl
- [ ] oshdb
- [ ] oshdb-api
- [ ] oshdb-util
- [ ] oshpbf-parser

**Comment by tyrasd** [comment]
findbugs is unmaintained (successor is spotbugs, see https://github.com/findbugsproject/findbugs#findbugs-is-now-spotbugs). closing in favour of #92
