### ISSUE TITLE
Implement Unit-Tests

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#96]
Like #91 we use as static analyses to check for code that is not covered by unit-tests.
Results can be seen here: https://reports.ohsome.org/oshdb/0.5.0-SNAPSHOT_master/204_c11a8e02/jacoco/

- [ ] oshdb
- [ ] oshdb-api
- [ ] oshdb-tool
- [ ] oshdb-util

**Comment by Hagellach37** [comment]
this is an ongoing effort and should be handled whenever changes are commited. closing this issue in favour of a better general process.
