### ISSUE TITLE
add warning when versions of an osh entity are missing

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#99]
opened by @tyrasd 

due to some data redactions, there might still be some missing data versions in our .osh.pbf files (and therefore in our oshdb files). For example, due to https://www.openstreetmap.org/changeset/59473904 we're missing versions 67 to 187 of https://www.openstreetmap.org/relation/192734:

```
r192734 v66 dV c13067600 t2012-09-11T10:43:56Z i714035 unamuori …
r192734 v188 dD c59473904 t2018-06-02T00:23:36Z i5164 uwoodpeck T M
r192734 v189 dV c59490832 t2018-06-02T17:47:36Z i5164 uwoodpeck …
```

see https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/148

**Comment by Hagellach37** [comment]
This warning would be visible only for users running their own cluster or OSHDB instance. We consider this out of scope for OSHDB.
